# Generated by Django 5.2.17 on 2026-08-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва / номер')),
                ('capacity', models.PositiveSmallIntegerField(default=35, verbose_name='Місткість')),
            ],
            options={
                'verbose_name': 'Кабінет',
                'verbose_name_plural': 'Кабінети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('days_per_week', models.PositiveSmallIntegerField(default=5, verbose_name='Днів на тиждень')),
                ('lessons_per_day', models.PositiveSmallIntegerField(default=7, verbose_name='Уроків на день')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклади',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Скорочення')),
                ('can_be_double', models.BooleanField(default=False, verbose_name='Може бути парним уроком')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('available_days', models.CharField(default='11111', help_text='5 або 6 символів 0/1, наприклад 11110 = пн-пт без пʼятниці', max_length=6, verbose_name='Доступні дні (пн-сб, 1=так)')),
                ('max_lessons_per_day', models.PositiveSmallIntegerField(default=8, verbose_name='Макс. уроків на день')),
            ],
            options={
                'verbose_name': 'Вчитель',
                'verbose_name_plural': 'Вчителі',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Паралель')),
                ('letter', models.CharField(max_length=2, verbose_name='Літера')),
                ('home_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.room', verbose_name='Основний кабінет')),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Класи',
                'ordering': ['grade', 'letter'],
                'unique_together': {('grade', 'letter')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.subject', verbose_name='Тільки для предмету'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('is_double', models.BooleanField(default=False)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduler.schedule')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.teacher')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['day', 'period', 'school_class'],
                'unique_together': {('schedule', 'room', 'day', 'period'), ('schedule', 'school_class', 'day', 'period'), ('schedule', 'teacher', 'day', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.PositiveSmallIntegerField(verbose_name='Годин на тиждень')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schoolclass', verbose_name='Клас')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.teacher', verbose_name='Вчитель')),
            ],
            options={
                'verbose_name': 'Навантаження',
                'verbose_name_plural': 'Навантаження',
                'unique_together': {('teacher', 'subject', 'school_class')},
            },
        ),
    ]
