# Generated by Django 5.2.17 on 2026-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='home_room',
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='letter',
            field=models.CharField(blank=True, max_length=2, verbose_name='Літера'),
        ),
    ]
