# Generated by Django 5.2.17 on 2026-08-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_home_room_letter_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='home_room',
            field=models.ForeignKey(blank=True, help_text='Для 1-4 класів: кабінет де проходять більшість уроків', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.room', verbose_name='Основний кабінет'),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='group',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1, 2, … якщо клас ділиться на групи для цього предмету. Порожньо = весь клас', null=True, verbose_name='Група'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('teacher', 'subject', 'school_class', 'group')},
        ),
    ]
