# Generated by Django 5.2.17 on 2026-08-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_add_group_restore_home_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('schedule', 'school_class', 'day', 'period'), ('schedule', 'teacher', 'day', 'period')},
        ),
        migrations.AddField(
            model_name='room',
            name='max_simultaneous',
            field=models.PositiveSmallIntegerField(default=1, help_text='Для спортзалу: 2, якщо можна вести два класи одночасно', verbose_name='Макс. класів одночасно'),
        ),
        migrations.AddField(
            model_name='subject',
            name='allow_shared_room',
            field=models.BooleanField(default=False, help_text='Наприклад, фізкультура: два класи одночасно в спортзалі', verbose_name='Дозволити спільний кабінет'),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_grade_diff',
            field=models.PositiveSmallIntegerField(default=2, help_text='1 = тільки та сама або сусідня паралель, 2 = ±2 класи тощо', verbose_name='Макс. різниця паралелей при спільному кабінеті'),
        ),
    ]
