# Generated by Django 5.2.17 on 2026-08-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_shared_room_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Розклад дзвінків',
                'verbose_name_plural': 'Розклади дзвінків',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='bell_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.bellschedule', verbose_name='Розклад дзвінків'),
        ),
        migrations.CreateModel(
            name='BellPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Урок №')),
                ('start_time', models.TimeField(verbose_name='Початок')),
                ('end_time', models.TimeField(verbose_name='Кінець')),
                ('bell_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='scheduler.bellschedule')),
            ],
            options={
                'verbose_name': 'Час уроку',
                'verbose_name_plural': 'Часи уроків',
                'ordering': ['number'],
                'unique_together': {('bell_schedule', 'number')},
            },
        ),
    ]
