# Generated by Django 5.2.17 on 2026-08-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_bell_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Колір'),
        ),
    ]
