# Generated by Django 5.1.5 on 2026-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_subject_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='available_days',
            field=models.CharField(default='11111', help_text='5 символів 0/1, наприклад 11110 = пн-чт без пʼятниці', max_length=5, verbose_name='Доступні дні (пн-пт, 1=так)'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='hours_per_week',
            field=models.DecimalField(decimal_places=1, help_text='Дробові значення (0.5, 1.5, 3.5…) = урок раз на два тижні', max_digits=4, verbose_name='Годин на тиждень'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('schedule', 'school_class', 'day', 'period', 'week'), ('schedule', 'teacher', 'day', 'period', 'week')},
        ),
    ]
