# Generated by Django 5.1.5 on 2026-08-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_decimal_hours_biweekly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
