# Generated by Django 5.1.5 on 2026-08-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_lesson_week_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('schedule', 'school_class', 'teacher', 'day', 'period', 'week'), ('schedule', 'teacher', 'day', 'period', 'week')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
