# Generated by Django 5.1.5 on 2026-08-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_lesson_add_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='unavailable_slots',
            field=models.JSONField(blank=True, default=None, help_text='Заблоковані уроки по днях (заповнюється через форму)', null=True, verbose_name='Недоступні слоти'),
        ),
    ]
