# Generated by Django 5.1.5 on 2026-08-28 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_teacher_unavailable_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='home_teacher',
            field=models.ForeignKey(blank=True, help_text='Уроки цього вчителя завжди отримують основний кабінет класу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_classes', to='scheduler.teacher', verbose_name='Класний керівник'),
        ),
    ]
