# Generated by Django 5.1.5 on 2026-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_add_home_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='subject',
        ),
        migrations.AddField(
            model_name='room',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Якщо не вибрано — загальний кабінет для будь-якого предмету', to='scheduler.subject', verbose_name='Тільки для предметів'),
        ),
    ]
