# Generated by Django 5.1.5 on 2026-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_room_subject_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='needs_specialized_room',
            field=models.BooleanField(default=False, help_text='Для 1-4 класів: фізкультура та інформатика йдуть у спеціалізований кабінет, решта предметів залишається у кабінеті класу', verbose_name='Потребує спеціалізованого кабінету'),
        ),
    ]
